# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

auto: true
markdown: rdiscount
permalink: pretty
pygments: true
safe: true
server: true

# -----------------------------------------------
# Paths
# -----------------------------------------------

images: /wpq/asset/image

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: Alex Poslavsky
author_email: alexander.poslavsky@gmail.com
title: WPQ
# url: /wpq

exclude: ["Procfile", "README.md", "_drafts", "Gemfile", "Gemfile.lock", ".rvmrc", ".gitignore","Makefile","config.rb","wpq.todo"]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: plovs
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: plovs
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user: plovs
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false
